### PR TITLE
fix: shabbos yuntif does not have a parsha

### LINKED ISSUE #16: Yom tov week
Last week the date was not צו it should of shown פסח

### PR DESCRIPTION
**Pull request by tam5**
Fixes #16.

Parsha will be returned as `null` if there is no parsha that week (the case of yuntif).

### CODE REVIEW

**Comment by zachweix** [comment]
I have 2 comments:
Now, it looks like you can never have Vezos Habracha as a Parsha, but it should probably show up as a Parsha for Simchas Torah
You added a new function comingShabbos, I'm leaving a comment there

**Comment by tam5** [comment]
1. Right, we don't have Vezos Habracha as a parsha anymore, that makes sense to me.
2. Can you post the comment? I don't see it yet

File: src/Getters/Parsha.php [hunk 1]
```diff
@@ -51,12 +51,17 @@ private function parshios($index, $format = null)
...
      *
-     * @return string
+     * @return string|null
      */
     private function parshasHashavua($galus = null)
     {
         $galus = $this->getGalusMode($galus);
 
+        // Yuntif does not have a parsha
+        if ($this->comingShabbos()->isYuntif() || $this->comingShabbos()->isCholHamoed()) {
```
Comment (zachweix) [inline src/Getters/Parsha.php:61]: This just checks if this coming Shabbos is Yuntif or Chol Hamoed. However, if today is Yuntif or Chol Hamoed, I assume we also don't want to have a Parsha (except Simchas Torah)?

**Comment by zachweix** [comment]
Sorry, I thought it was submitted. I just submitted now

File: src/Getters/Getters.php [hunk 2]
```diff
@@ -2,12 +2,26 @@
...
 
+    /**
+     * Get the date of the next Shabbos.
+     *
+     * @return $this
+     */
+    public function comingShabbos()
+    {
+        return $this->dayOfWeek !== Carbon::SATURDAY
+            ? (clone $this)->next('Saturday')
```
[the remark this answers is not in the document]
Comment (tam5) [reply src/Getters/Getters.php:21]: thanks

File: src/Getters/Getters.php [hunk 3]
```diff
@@ -2,12 +2,26 @@
...
+            : $this;
```
[the remark this answers is not in the document]
Comment (tam5) [reply src/Getters/Getters.php:22]: sure

File: src/Getters/Parsha.php (hunk 1 above)
Comment (tam5) [reply src/Getters/Parsha.php:61]: They way the `parsha` works is always to get that week's parsha, rather than the parsha of the current day. On a random Wednesday the only applicable parsha is that of the coming shabbos, so I see no difference if it happened to be yuntif on that wednesday

Comment (zachweix) [reply src/Getters/Parsha.php:61]: After thinking about this a little more, I think that you shouldn't check if this coming Shabbos is Yuntif or Chol Hamoed. Instead you should check if today is Shabbos, and if not then return the Parsha for this coming Shabbos. Then the next check should just be if today is Yuntif or Chol Hamoed. The bonus is that you can get rid of the helper method and won't potentially have to create two more variables that are immediately orphaned. Granted, this is nit-picky, but I think it makes it clearer when looking at the code what it is doing
